posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

simplesocial/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from simplesocial import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^test/$',views.TestPage.as_view(),name = "test"),
    url(r'^thanks/$',views.ThanksPage.as_view(),name = "thanks"),
    url(r'^$',views.HomePage.as_view(),name = "home"),
    url(r'^accounts/',include('accounts.urls',namespace = 'accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
]

posts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse
from groups.models import Group
from accounts.models import User

from django import template
register = template.Library()
# Create your models here.

class Post(models.Model):
    message = models.TextField()
    created_at = models.DateField(auto_now = True)
    user = models.ForeignKey(User,related_name='posts',on_delete = models.CASCADE)
    group = models.ForeignKey(Group,related_name='posts',on_delete = models.CASCADE)

    def __str__(self):
        return self.message

    def get_absolute_url(self):
        return reverse('posts:single',kwargs = {'username':self.user.username,'pk':self.pk})

    class Meta():
        ordering = ['-created_at']

posts/forms.py
from django import forms

from posts import models


class PostForm(forms.ModelForm):
    class Meta:
        fields = ("message", "group")
        model = models.Post

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super(PostForm,self).__init__(*args, **kwargs)
        if user is not None:
            self.fields["group"].queryset = models.Group.objects.filter(members = user)

posts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from django.core.urlresolvers import reverse_lazy
from django.http import Http404
from django.views import generic
from django.shortcuts import get_object_or_404

from braces.views import SelectRelatedMixin

from . import forms
from . import models

from accounts.models import User

# Create your views here.

class PostList(SelectRelatedMixin,generic.ListView):
    model = models.Post
    select_related = ('user','group')

class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        if self.request.user.is_authenticated:
            self.username = get_object_or_404(User,username__iexact=self.kwargs.get("username"))
            return models.Post.objects.filter(user=self.username)
        else:
            raise Http404

class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super(PostDetail,self).get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get("username"))

class CreatePost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    form_class = forms.PostForm
    model = models.Post

    def get_form_kwargs(self):
         kwargs = super(CreatePost,self).get_form_kwargs()
         kwargs.update({"user": self.request.user})
         return kwargs

    def form_valid(self,form):
        self.object = form.save(commit = False)
        user = get_object_or_404(User,username__iexact=self.request.user.username)
        self.object.user = user
        self.object.save()
        return super(CreatePost,self).form_valid(form)

class DeletePost(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    model = models.Post
    select_related = ('user','group')
    success_url = reverse_lazy('posts:all')

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super(DeletePost,self).delete(*args, **kwargs)

posts/templates/posts/_post.html
<div class="post media">
	<h3>{{ post.message|safe }}</h3>
	<div class="media-body">
		<h5 class="media-heading">
			<span class="username"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></span>
			<time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a></time>
			{% if post.group %}
			<span class="group-name">in {{ post.group.name }}</span>
			{% endif %}
		</h5>

		<div class="media-footer">
			{% if user.is_authenticated and post.user.username == request.user.username and not hide_delete %}
				<a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
					<span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
					<span class="text-danger icon-label">Delete</span>
				</a>
			{% endif %}
		</div>
	</div>
</div>

posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
  <div class="post-page">
    <div class="container">
      <div class="row">
        {% block prepost %}{% endblock %}
        {% block post_content %}{% endblock %}
        {% block post_post %}{% endblock %}
      </div>

    </div>

  </div>

{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}
  <h3>Are you sure you want to delete this post?</h3>

  <div class="posts">

    <form method="POST">
      {% csrf_token %}
        <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
        <a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-large btn-default">Cancel</a>
    </form>

  </div>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
  <div class="col-md-8">
    {% include "posts/_post.html" %}
  </div>

{% endblock %}

posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}

{% load bootstrap3 %}

{% block post_content %}
  <h4>Create New Post!</h4>

  <form id="postForm" action="{% url 'posts:create' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}

    <input type="submit" value="Post" class="btn btn-primary btn-large">

  </form>

{% endblock %}

posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}

{% block post_content %}
  <div class="col-md-8">
    {% for post in post_list %}
      {% include "posts/_post.html" %}
    {% endfor %}
    </div>
{% endblock %}

posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}

  <div class="col-md-4">
    {% for post in object_list %}
      {% include "posts/_post.html" %}
    {% endfor %}
  </div>

{% endblock %}